name: CI

on:
  push:
    branches:
      - 2.x
  pull_request:
    branches:
      - 2.x
jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '24'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check code
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Check types
        run: npm run typecheck

      - name: Check boundaries
        run: npm run depcruise

      - name: Run tests
        run: npm run test

      - name: Check packages
        run: npm run publint
