name: Publish
permissions:
  contents: write

on:
  release:
    types: [ published ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install

      - name: publish
        run: ./.github/bin/publish ${{ github.event.release.tag_name }} 2.x
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
