#!/bin/bash

set -e
set -o pipefail

TAG=$1
VERSION=${TAG#v}
npm version "$VERSION" --no-git-tag-version
git config user.name "koala[bot]"
git config user.email "koala[bot]@users.noreply.github.com"
git add .
git commit -m "chore: bump version to $VERSION"
git push origin HEAD
